namespace VisitorManagementAI.Models;

/// <summary>
/// Represents the response from the visitor query service.
/// </summary>
/// <param name="AiResponseText">The natural language response generated by the AI.</param>
/// <param name="DataContext">The raw data context used to generate the response (optional).</param>
/// <param name="ToolUsed">The name of the tool used to fetch data (optional).</param>
/// <param name="Timestamp">The timestamp when the response was generated.</param>
public record VisitorQueryResponse(string AiResponseText, string? DataContext, string? ToolUsed, DateTime Timestamp);